DROP DATABASE IF EXISTS :database;
DROP ROLE IF EXISTS :user;
CREATE ROLE :user WITH LOGIN CREATEDB PASSWORD :'password';
CREATE DATABASE :database WITH OWNER :user;
\c :database
CREATE EXTENSION postgis;
