DROP DATABASE IF EXISTS :database;
DROP ROLE IF EXISTS geoserver;
CREATE ROLE geoserver WITH LOGIN CREATEDB PASSWORD 'geoserver';
CREATE DATABASE :database WITH OWNER geoserver;
\c :database
CREATE EXTENSION postgis;
